script check_system_requirements improved

diff --git a/src/scripts/check_system_requirements b/src/scripts/check_system_requirements
--- a/src/scripts/check_system_requirements
+++ b/src/scripts/check_system_requirements
@@ -1,13 +1,17 @@
 #!/bin/bash
 
+cd `dirname $0`
+ROOT=`./_get_application_path`../
+
 assert_command_exists () {
 	cmd=$1
 	echo -n "command $cmd exists... "
 	if [ "`which $cmd`" = "" ]; then
 		echo "fail"
-		exit 1
+		echo "!!  command $cmd is not installer"
+	else	
+		echo "ok"
 	fi
-	echo "ok"
 }
 
 assert_php_function_exists () {
@@ -16,22 +20,70 @@ assert_php_function_exists () {
 	src="echo function_exists('$fn') ? 'yes' : 'no';"
 	if [ `/usr/bin/env php -r "$src"` != "yes" ]; then
 		echo "fail"
-		exit 1
+		echo "!!  in PHP there is no function $fn"
+	else	
+		echo "ok"
 	fi
-	echo "ok"
 }
 
 assert_command_exists 'env'
 assert_command_exists 'wget'
 assert_command_exists 'php'
+assert_command_exists 'pear'
 assert_command_exists 'psql'
 assert_command_exists 'git'
 assert_command_exists 'fgrep'
 assert_command_exists 'tee'
+assert_command_exists 'msgconv'
+assert_command_exists 'msgfmt'
+assert_command_exists 'msgmerge'
+assert_command_exists 'xgettext'
 
 assert_php_function_exists 'pg_connect'
 assert_php_function_exists 'gettext'
 assert_php_function_exists '_'
 assert_php_function_exists 'posix_getpid'
+assert_php_function_exists 'get_called_class'
+assert_php_function_exists 'spl_autoload_register'
 
-# TODO: version of php must be >= 5.3
+# version of php must be >= 5.3
+echo -n "version of php is 5.3 or newer... "
+php_version=`php -v | head -1 | cut -d ' ' -f 2`
+if [ ! "$php_version" \> "5.3." ]; then
+	echo "fail"
+	echo "!!  version of currently installed php is $php_version"
+else	
+	echo "ok";
+fi
+
+# checking for tmp and log directories
+for i in "tmp" "log"; do
+	dir="$ROOT$i"
+	echo -n "directory $i exists... ";
+	if [ ! -d $dir ]; then
+		echo "fail"
+		echo "!!  do the following:"
+		echo "!!  $ mkdir -m 0757 $dir"
+	else	
+		echo "ok"
+	fi
+	# TODO: directory must be writable for others (webserver user)
+done
+
+echo -n "PHPUnit2 is installed... ";
+cat << EOF | php
+<?php
+@include_once 'PHPUnit2/Framework/TestSuite.php';
+@include_once 'PHPUnit2/Framework/TestCase.php';
+@include_once 'PHPUnit2/TextUI/ResultPrinter.php';
+@include_once 'Benchmark/Timer.php';
+if(class_exists('PHPUnit2_Framework_TestCase')){
+	echo "ok\n";
+}else{
+	echo "fail\n";
+	echo "!!  do the following:\n";
+	echo "!!  $ sudo pear install --alldeps PHPUnit2\n";
+}
+EOF
+
+exit $ret
