working on testing

diff --git a/src/scripts/run_unit_tests b/src/scripts/run_unit_tests
--- a/src/scripts/run_unit_tests
+++ b/src/scripts/run_unit_tests
@@ -37,7 +37,7 @@ if(preg_match("/^5/",phpversion())){
 if(PHP4){
 	include_once 'PHPUnit.php';
 	if(!class_exists("PHPUnit_TestCase")){
-		echo "Missing dependency: class PHPUnit2_Framework_TestCase\n";
+		echo "Missing dependency: class PHPUnit_TestCase\n";
 		echo "The following command may help you\n";
 		echo "\n";
 		echo " $ sudo pear install PHPUnit\n";
@@ -52,20 +52,29 @@ if(PHP5){
 	include_once 'Benchmark/Timer.php';
 
 	if(!class_exists("PHPUnit2_Framework_TestCase")){
-		echo "Missing dependency: class PHPUnit2_Framework_TestCase\n";
-		echo "The following command may help you\n";
-		echo "\n";
-		echo " $ sudo pear install --alldeps PHPUnit2\n";
-		echo "\n";
+		echo "************************************************************\n";
+		echo "*  Missing dependency: class PHPUnit2_Framework_TestCase   *\n";
+		echo "*  The following command may help you                      *\n";
+		echo "*                                                          *\n";
+		echo "*  $ sudo pear install --alldeps PHPUnit2                  *\n";
+		echo "*                                                          *\n";
+		echo "************************************************************\n";
 		exit(1);
 	}
 }
 
-isset($argv) || $argv = array();
+isset($argv) || ($argv = array());
 
+$SCRIPT = array_shift($argv);
+$DIR = "";
 $RUN_TESTS_ONLY = array();
-for($i=1;$i<sizeof($argv);$i++){
-	$RUN_TESTS_ONLY[] = $argv[$i];
+while($_a = array_shift($argv)){
+	if(is_dir($_a)){ $DIR = $_a; continue; }
+	$RUN_TESTS_ONLY[] = $_a;
+}
+if($DIR){
+	$DIR = preg_replace('/([^\/])$/','\1/',$DIR);
+	chdir($DIR);
 }
 
 if(PHP4){
@@ -137,16 +146,16 @@ while(list($filename,$classname) = each($ALLOWED_DANGEROUS_TESTS)){
 }
 
 if(sizeof($tests_to_execute)==1){
-	_test_runner($tests_to_execute[0]);
+	_test_runner($tests_to_execute[0],$DIR:);
 	exit;
 }
 
 
 foreach($tests_to_execute as $_f){
-	$cmd = escapeshellcmd($argv[0])." ".escapeshellarg($_f)." 2>&1";
+	$cmd = escapeshellcmd($SCRIPT)." ".escapeshellarg($_f)." 2>&1";
 	if(isset($_SERVER["_"])){
 		// v $_SERVER["_"] je interpret PHP: /usr/bin/php
-		$cmd = escapeshellcmd($_SERVER["_"])." ".escapeshellarg($argv[0])." ".escapeshellarg($_f)." 2>&1";
+		$cmd = escapeshellcmd($_SERVER["_"])." ".escapeshellarg($SCRIPT)." ".escapeshellarg($_f)." 2>&1";
 	}
 	passthru($cmd);
 }
@@ -169,7 +178,7 @@ function _test_inobj_error_handler($values){
 	exit;
 }
 
-function _test_runner($filename){
+function _test_runner($filename,$DIR){
 	$classname = preg_replace('/\.[^.]*$/',"",$filename);
 	$classname = preg_replace('/^!/',"",$classname);
 	$alt_classname = preg_replace('/_/',"",$classname);
@@ -179,7 +188,7 @@ function _test_runner($filename){
 	if(class_exists($alt_classname)){ $classname = $alt_classname; }
 
 	if(!class_exists($classname)){
-		echo "--- $filename\n";
+		echo "--- $DIR$filename\n";
 		echo "!!! class $classname doesn't exist\n";
 		return;
 	}
@@ -187,7 +196,7 @@ function _test_runner($filename){
 	if(PHP4){
 		$suite  = new PHPUnit_TestSuite($classname);
 		$result = PHPUnit::run($suite);
-		echo "--- $filename\n";
+		echo "--- $DIR$filename\n";
 		print $result->toString();
 	}
 	if(PHP5){
@@ -202,7 +211,7 @@ function _test_runner($filename){
 		$result = $suite->run();
 		$timer->stop();
 
-		echo "--- $filename\n";
+		echo "--- $DIR$filename\n";
 		$printer->printResult($result, $timer->timeElapsed());
 	}
 }
