[Atk14] Scripts run_unit_tests and check_system tuned

diff --git a/src/scripts/run_unit_tests b/src/scripts/run_unit_tests
--- a/src/scripts/run_unit_tests
+++ b/src/scripts/run_unit_tests
@@ -3,6 +3,12 @@
 /**
  * A test runner. Part of ATK14 Framework <http://www.atk14.net/>
  *
+ * Checking that all required dependencies are met:
+ *
+ *   $ run_unit_tests --check-dependencies && echo "ok"
+ *   # or
+ *   $ run_unit_tests -c && echo "ok"
+ *
  * In working directory it searches for tc_*.php files. Every of them loads and runs tests.
  *
  *   $ run_unit_tests
@@ -29,7 +35,7 @@
  * Automatization in testing
  * -------------------------
  *
- *   $ cd /path/to/test_files/ ; run_unit_tests && echo "TESTS ARE OK" || echo "THERE WERE ERRORS"
+ *   $ cd /path/to/test_files/ && run_unit_tests && echo "TESTS ARE OK" || echo "THERE WERE ERRORS"
  *
  */
 error_reporting(255);
@@ -55,6 +61,7 @@ $HOME = getenv("HOME"); // "/home/yarri"
 isset($_ENV["PWD"]) && chdir($_ENV["PWD"]);
 
 isset($argv) || ($argv = array());
+$arguments = getopt("c",array("check-dependencies"));
 
 $SCRIPT = array_shift($argv);
 $SCRIPT_ABSOLUTE = __FILE__;
@@ -82,6 +89,19 @@ foreach(array(
 	}
 }
 
+$error_message = 
+"***************************************************************\n".
+"*  Missing dependency: PHPUnit or PHPUnit2                    *\n".
+"*  The following command may help you:                        *\n".
+"*                                                             *\n".
+"*  $ composer global require \"phpunit/phpunit=4.8.*|5.7.*\"    *\n".
+"*                                                             *\n".
+"*  or for the installation of the very old PHPUnit2 execute:  *\n".
+"*                                                             *\n".
+"*  $ sudo pear install --alldeps PHPUnit2                     *\n".
+"*                                                             *\n".
+"***************************************************************\n";
+
 if($exists) {
 	// $ composer global require "phpunit/phpunit=4.8.*"
 	require("$dir/$autoload");
@@ -101,25 +121,24 @@ if($exists) {
 	include_once 'Benchmark/Timer.php';
 
 	if(!class_exists("PHPUnit2_Framework_TestCase")){
-		echo "***************************************************************\n";
-		echo "*  Missing dependency: class PHPUnit_Framework_TestCase       *\n";
-		echo "*  The following command may help you:                        *\n";
-		echo "*                                                             *\n";
-		echo "*  $ composer global require \"phpunit/phpunit=4.8.*|5.7.*\"    *\n";
-		echo "*                                                             *\n";
-		echo "*  or for the installation of the very old PHPUnit2 execute:  *\n";
-		echo "*                                                             *\n";
-		echo "*  $ sudo pear install --alldeps PHPUnit2                     *\n";
-		echo "*                                                             *\n";
-		echo "***************************************************************\n";
+		echo $error_message;
 		exit(1);
 	}
 }
+
+if(isset($arguments["c"]) || isset($arguments["check-dependencies"])){
+	exit(0);
+}
+
 
 if(PHPUNIT2){
 	eval("class tc_super_base extends PHPUnit2_Framework_TestCase{ }");
 	eval("class TcSuperBase extends PHPUnit2_Framework_TestCase{ }");
 }else{
+	if(!class_exists('PHPUnit\Framework\TestCase') && !class_exists('PHPUnit_Framework_TestCase')){
+		echo $error_message;
+		exit(1);
+	}
 	if(class_exists('PHPUnit\Framework\TestCase')){
 		eval("class tc_super_base extends PHPUnit\Framework\TestCase{ }");
 		eval("class TcSuperBase extends PHPUnit\Framework\TestCase{ }");
